fix: docker compose failed with sharp error, change to debian node instead of alpine
- Node-js v22.22.2
hugo-indiekit@1.0.0 start npx indiekit serve
/app/node_modules/sharp/Lib/sharp-js:120
throw new Error(help-join('\\n')):
^
Error: Could not load the "sharp" module using the linuxmusl-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
See [https://sharp.pixelplumbing.com/install#cross-platform](https://sharp.pixelplumbing.com/install#cross-platform)
- Add platform-specific dependencies:
npm install --os=linux --libc=musl--cpu=arm64 sharp